server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://demo:test1234@docdb-2023-08-23-16-44-39.cluster-cvtk2sumblfm.us-east-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: demodb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration